- README.md
PSoC provides swag and free subscriptions to participants.
> Update website for PSoC - PClub Summer of Code

- README.md
Semester Long Projects by Dhirubhai Ambani Institute of Information and Communication Technology is a Hackathon cum Internship opportunity.
> Added SLoP by DAIICT

- README.md
Issue #18
Added HackinCodes Contributor's Hack to Open Source Competitions.
> Adding HackinCodes Contributor's Hack 

- README.md
Regarding Issue #17 
Fixed the link to the Timeline.
> Fixed timeline link of Open Summer of Code

- README.md
Fixed major broken links "RubyMe, PClub Summer of Code etc"
> Fixed various Broken Links

- README.md
Added a few more links, repaired PClub SOC.
> Repaired PClub SOC. Added timeline - PClub SOC and 24PR

- README.md
Fixed #27 
Removed OWASP SOC from README.md
> Fixed OWASP broken Link

- README.md
Script Winter of Code is an open-source program envisioned by the Script Foundation. It aims to bring students into the world of open source development and see the power of unified problem-solving in real time.
> Added Script Winter of Code

- README.md
> Added DevScript Winter of Code

- README.md
> Removed typo in Millennium Fellowship

- .github/linters/mlc_config.json
- .github/workflows/md_link.yml
@deepanshu1422 Can you please review.
This will check the whole README for dead links.
> Markdown Link Action

- README.md
I have removed the programs as of now.
Would review all the links once before merging
Potential Fixes #60
> Removed dead program, Fixes #60

- README.md
#63 and #51 
Added the section of Start Date and End Date of some programs but need to do more
> Added Start Date and End Date

- README.md
new link is https://swoc.scriptindia.org/#/
> Updated broken swoc.tech link

- README.md
Added these Open-Source-Program -> CWoC , GWoC, HCSSoC
Fixed issue :-  #83
<br>
Hey @deepanshu1422 , Checkout this PR and if everything is fine, kindly merge it .
Thanks.........
> Added some more OS Programs

- README.md
Fixed issue :- #86
[ Added IIIT-Kalyani Winter of code 2.0 in the -> University SoC/WoC section. ]
Hey @deepanshu1422 , Checkout this PR and if everything is fine, kindly merge it .
Thanks.........
> Added IIIT-Kalyani Winter of code 2.0 in the -> University SoC/WoC section.

- README.md
I've added the updated program details for 2022. Thanks! - MLH Team
> Updated MLH fellowship dates for 2022 

- README.md
Added season of bitcoin program
> added season of bitcoin program

- README.md
I am a millennium fellow (class of 2019) and have updated the program schedule. It is a semester-long program starting around June of every year and ending by December. Fellows graduate in January
> Added start and end dates of Millennium Fellowship.

- README.md
[Devtron](https://github.com/devtron-labs/devtron) is an open-source software delivery workflow for Kubernetes that helps you build, test, deploy, and debug all your applications on Kubernetes. It is an open-source organization on a mission to democratize [Kubernetes adoption](https://devtron.ai/devops-in-a-box.html).
> added Devtron Opensource Internship

- README.md
Remove discontinued GNOME program from list!
> Update README.md -> Remove discontinued program 

- README.md
- Fix 'Summer of Bitcoin' name
- Add Microsoft Reinforcement Learning Open Source Fest
Signed-off-by: Hollow Man <hollowman@opensuse.org>
> Fix 'Summer of Bitcoin' name; Add Microsoft Reinforcement Learning Open Source Fest

- README.md
> Updated JGEC Winter code link

- README.md
added link for 'Social Summer of Code' under Open source under Open Source competitions.
> Update README.md (added open source competition)
